const fs = require("fs");
var nodemailer = require('nodemailer');
const Role = require("../model/role.model");

const apiResponse = (result =null, status=true, msg="Success") => {
    let data = {
        result: result,
        status: status,
        msg: msg
    }
    return data;
}

const deleteImage = (image) => {
    return new Promise((resolve, reject) => {
        let path = process.cwd()+"/uploads/"+image;
        
        try {
            fs.unlink(path, (err, success) => {
                if(err){
                    reject(err);
                } else {
                    resolve(success);
                }
            })
        } catch(err) {
            reject(err);
        }   

    })
}
const generateRandomStr = (len = 100) => {
    let chars = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    let str_len = chars.length;
    let random = "";
    for(let i = 0; i < len; i++) {
        let posn = Math.floor(Math.random()*str_len);
        random += chars[posn]
    }
    return random;
}

const sendEmail = (to, subject, msg) => {
    var transport = nodemailer.createTransport({
        host: "smtp.mailtrap.io",
        port: 2525,
        auth: {
          user: "025b087bc187dd", //generated by Mailtrap
          pass: "1a5eaad072af1d" //generated by Mailtrap
        }
      });
    var mailOptions = {
        from: '"No reply" <noreply@test.com>',
        to: to,
        subject: subject,
        text: msg,
        html: msg
    };
    transport.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log("Mailer: ",error);
        }
        console.log('Message sent: %s', info.messageId);
    });
}


const getRoleById = async (role_id) => {
    let roles = Role.findById(role_id);
    return roles;
}
module.exports = {getRoleById, apiResponse, deleteImage, generateRandomStr, sendEmail};